
import { Inter } from 'next/font/google'
import { Work_Sans, Quattrocento_Sans } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'

export const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '400', '300'],
  variable: '-inter-font'
})

export const workSans = Work_Sans({
  weight: ['200', '400', '300'],
  subsets: ['latin'],
  variable: '-workSans-font'
})

export const quattrocento = Quattrocento_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id='body' className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
