
import { Inter } from 'next/font/google'
import { Work_Sans } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Hero from '@/components/Hero'
import Proyects from '@/components/Proyects'
import Footer from '@/components/Footer'
import Form from '@/components/Form/Form'
import Container from '@/components/Container'

const inter = Inter({ subsets: ['latin'] })
const workSans = Work_Sans({
  subsets: ['latin'],
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id='body' className="text-[#E3E4E6] font-['Montserrat']">
        <div className='md:max-w-[80%] w-[100%] mx-auto overflow-hidden  md:overflow-visible '>
            <NavBar className={workSans.className} />
            <Hero />
            <Proyects />
            <Form />
            <Footer />
        </div>
        {children}
      </body>
    </html>
  )
}
